language: objective-c

osx_image: xcode8.2

install:
  - brew install doxygen

env:
  - CMD_SWIFT_TAG=swift-3.0.2-release

script:
  - mkdir apple
  - git clone https://github.com/apple/swift apple/swift
  - pushd apple/swift
  - git checkout $CMD_SWIFT_TAG
  - utils/update-checkout --clone
  - popd
  - doxygen doxygen.config
  - pushd html
  - make
